- job:
    name: ansible-runner-build-image
    parent: ansible-build-docker-image
    description: Build docker images
    timeout: 2700
    provides: ansible-runner-container-image
    vars:
      docker_images:
        - context: .
          repository: ansible/ansible-runner
          target: ansible-runner
          tags:
            # If zuul.tag is defined: [ '3', '3.19', '3.19.0' ].  Only works for 3-component tags.
            # Otherwise: ['latest']
            &imagetag "{{ zuul.tag is defined | ternary([zuul.get('tag', '').split('.')[0], '.'.join(zuul.get('tag', '').split('.')[:2]), zuul.get('tag', '')], ['latest']) }}"

- project:
    check:
      jobs:
        - ansible-buildset-registry
        - ansible-runner-build-image
